module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Lato', 'ui-sans-serif', 'system-ui'],
        serif: ['ui-serif', 'Georgia'],
        mono: ['ui-monospace', 'SFMono-Regular'],
        display: ['Lato'],
        body: ['ui-sans-serif'],
      },
      fontSize: {
        xxs: '.5rem',
      },
      colors: {
        linkedin: '#0A66C2',
        swift: '#FF0524',
        flutter: '#4BD2FD',
        mongodb: '#11924F',
        mysql: '#017891',
        postgresql: '#2F6792',
        graphql: '#E632AD',
        elixir: '#644473',
        rust: '#000',
        kotlin: '#7F52FF',
        rust: '#634B3B',
        dart: '#0799C4',
        laravel: '#FF2A1B',
        javascript: '#FAD924',
        php: '#8892BF',
        react: '#61DAFB',
        vue: '#33A06F',
        angular: '#DD0031',
        aws: '#FF9D00',
        java: '#C74634',
        go: '#00ADD8',
        ionic: '#3581FF',
        nuxtjs: '#00DC82',
        nextjs: '#000000',
        nestjs: '#E11E4D',
        supabase: '#44D191',
        gatsby: '#663399',
        firebaseFrom: '#F5830C',
        firebaseTo: '#FFCB2B',
        solidity: '#666666',
        redux: '#764ABC',
        vuex: '#3EAF7C',
        pinia: '#F7D336',
        tdd: '#777777',
        bdd: '#999999',
        ios: '#1D1D1D',
        rxswift: '#FF4DB3',
        linux: '#F5BE04',
        reactnative: '#61DAFB',
        docker: '#2496ED',
        kubernetes: '#2E6CE6',
        terraform: '#5C4EE5',
        android: '#3ADD85',
        rabbitmq: '#FF6600',
        kafka: '#444444',
        prometheus: '#E6522C',
        datadog: '#632DA8',
        wordpress: '#3B94B1',
        rxjava: '#DE0D8F',
        rxjs: '#C1128E',
        microservices: '#000000',
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: [
      {
        cmyk: {
          ...require('daisyui/src/colors/themes')['[data-theme=cmyk]'],
          primary: '#00ddff',
          secondary: '#fc0476',
        },
      },
    ],
    styled: true,
  },
}
